export const languages = [

	{ id: 1, name: "Chinese", nativeName: "汉语 | 漢語 or 中文" },
	{ id: 2, name: "Mandarin", nativeName: "官话 | 官話" },
	{ id: 3, name: "Spanish", nativeName: "Español" },
	{ id: 4, name: "English", nativeName: "English" },
	{ id: 6, name: "Hindi", nativeName: "हिन्दी" },
	{ id: 7, name: "Portuguese", nativeName: "Português" },
	{ id: 8, name: "Bengali", nativeName: "বাংলা" },
	{ id: 9, name: "Brazilian Portuguese", nativeName: "Brasileiro, Português do Brasil" },
	{ id: 10, name: "Russian", nativeName: "Русский" },
	{ id: 11, name: "Japanese", nativeName: "日本語" },
	{ id: 12, name: "Punjabi", nativeName: "ਪੰਜਾਬੀ | پنجابى" },
	{ id: 13, name: "German", nativeName: "Deutsch" },
	{ id: 14, name: "Javanese", nativeName: "ꦧꦱꦗꦮ | Basa Jawa" },
	{ id: 15, name: "Wu", nativeName: "吴语 | 吳語" },
	{ id: 16, name: "Malay", nativeName: "Bahasa Melayu | بهاس ملايو" },
	{ id: 17, name: "Korean", nativeName: "한국어" },
	{ id: 18, name: "Vietnamese", nativeName: "Tiếng Việt" },
	{ id: 19, name: "Telugu", nativeName: "తెలుగు" },
	{ id: 20, name: "French", nativeName: "Français" },
	{ id: 21, name: "Marathi", nativeName: "मराठी" },
	{ id: 22, name: "Turkish", nativeName: "Türkçe" },
	{ id: 23, name: "Urdu", nativeName: "اُردُو" },
	{ id: 24, name: "Tamil", nativeName: "தமிழ்" },
	{ id: 25, name: "Italian", nativeName: "Italiano" },
	{ id: 26, name: "Cantonese (Yue)", nativeName: "廣州話" },
	{ id: 27, name: "Persian (Farsi)", nativeName: "فارسی" },
	{ id: 28, name: "Gujarati", nativeName: "ગુજરાતી" },
	{ id: 29, name: "Indonesian", nativeName: "Bahasa Indonesia" },
	{ id: 30, name: "Bhojpuri", nativeName: "भोजपुरी" },
	{ id: 31, name: "Polish", nativeName: "Polski" },
	{ id: 32, name: "Kurdish Languages", nativeName: "Kurdî | كوردی" },
	{ id: 33, name: "Pashto", nativeName: "پښتو" },
	{ id: 34, name: "Kannada", nativeName: "ಕನ್ನಡ" },
	{ id: 35, name: "Sundanese", nativeName: "ᮘᮞ ᮞᮥᮔ᮪ᮓ | Basa Sunda" },
	{ id: 36, name: "Malayalam", nativeName: "മലയാളം" },
	{ id: 37, name: "Maithili", nativeName: "मैथिली | মৈথিলী" },
	{ id: 38, name: "Hausa", nativeName: "Harshen Hausa | هَرْشَن هَوْسَ" },
	{ id: 39, name: "Odia (Oriya)", nativeName: "ଓଡ଼ିଆ" },
	{ id: 40, name: "Burmese", nativeName: "မြန်မာစာ" },
	{ id: 41, name: "Ukrainian", nativeName: "українська мова" },
	{ id: 42, name: "Yoruba", nativeName: "Èdè Yorùbá" },
	{ id: 43, name: "Tagalog (Filipino)", nativeName: "Tagalog" },
	{ id: 44, name: "Uzbek", nativeName: "Oʻzbek | Ўзбек | اوزبیک" },
	{ id: 45, name: "Fula", nativeName: "Fulfulde" },
	{ id: 46, name: "Amharic", nativeName: "አማርኛ" },
	{ id: 47, name: "Sindhi", nativeName: "سنڌي | सिन्धी" },
	{ id: 48, name: "Igbo", nativeName: "Asụsụ Igbo" },
	{ id: 49, name: "Romanian", nativeName: "Română" },
	{ id: 50, name: "Oromo", nativeName: "Afaan Oromo" },
	{ id: 51, name: "Azerbaijani (Azeri)", nativeName: "Azərbaycan" },
	{ id: 52, name: "Dutch", nativeName: "Nederlands" },
	{ id: 53, name: "Cebuano (Visayan)", nativeName: "Binisaya" },
	{ id: 54, name: "Thai", nativeName: "ภาษาไทย" },
	{ id: 55, name: "Lao", nativeName: "ພາສາລາວ" },
	{ id: 56, name: "Serbo-Croatian", nativeName: "Srpskohrvatski | hrvatskosrpski | српскохрватски | хрватскосрпски" },
	{ id: 57, name: "Malagasy", nativeName: "Malagasy" },
	{ id: 58, name: "Nepalese (Nepali)", nativeName: "नेपाली" },
	{ id: 59, name: "Sinhala (Sinhalese)", nativeName: "සිංහල" },
	{ id: 60, name: "Khmer", nativeName: "ភាសាខ្មែរ" },
	{ id: 61, name: "Taiwanese", nativeName: "臺灣話 / 臺語" },
	{ id: 62, name: "Swahili", nativeName: "Kiswahili" },
	{ id: 63, name: "Madurese", nativeName: "Madhura, Basa Mathura بَهاسَ مَدورا" },
	{ id: 64, name: "Somali", nativeName: "Af-Soomaali" },
	{ id: 65, name: "Assamese (Asamiya)", nativeName: "অসমীয়া" },
	{ id: 66, name: "Hungarian", nativeName: "Magyar" },
	{ id: 67, name: "Greek", nativeName: "ελληνικά" },
	{ id: 68, name: "Kazakh", nativeName: "Qazaqşa | Қазақша | قازاق تىلى" },
	{ id: 69, name: "Zulu", nativeName: "isiZulu" },
	{ id: 70, name: "Afrikaans", nativeName: "Afrikaans" },
	{ id: 71, name: "Haitian Creole", nativeName: "Kreyòl Ayisyen" },
	{ id: 72, name: "Czech", nativeName: "Čeština" },
	{ id: 73, name: "Ilokano", nativeName: "Ilocano" },
	{ id: 74, name: "Dari", nativeName: "دری" },
	{ id: 75, name: "Swedish", nativeName: "Svenska" },
	{ id: 76, name: "Quechua", nativeName: "Kechua" },
	{ id: 77, name: "Kirundi (Rundi)", nativeName: "Ikirundi" },
	{ id: 78, name: "Serbian", nativeName: "српски | srpski" },
	{ id: 80, name: "Hiligaynon", nativeName: "Ilonggo" },
	{ id: 81, name: "Xhosa", nativeName: "isiXhosa" },
	{ id: 82, name: "Albanian", nativeName: "shqip" },
	{ id: 83, name: "Catalan", nativeName: "Català" },
	{ id: 84, name: "Belarusian", nativeName: "беларуская мова" },
	{ id: 85, name: "Bulgarian", nativeName: "български език" },
	{ id: 86, name: "Armenian", nativeName: "հայերեն" },
	{ id: 87, name: "Flemish", nativeName: "Belgisch-Nederlands" },
	{ id: 88, name: "Mongolian", nativeName: "Монгол хэл | ᠮᠣᠨᠭᠭᠣᠯ ᠬᠡᠯᠡ" },
	{ id: 89, name: "Danish", nativeName: "Dansk" },
	{ id: 90, name: "Croatian", nativeName: "hrvatski" },
	{ id: 91, name: "Tatar", nativeName: "татар теле | tatar tele | تاتار تيلی" },
	{ id: 92, name: "Hebrew", nativeName: "עִבְרִית" },
	{ id: 93, name: "Slovak", nativeName: "Slovenčina | Slovenský jazyk" },
	{ id: 94, name: "Finnish", nativeName: "Suomen kieli" },
	{ id: 95, name: "Norwegian", nativeName: "Norsk" },
	{ id: 96, name: "Georgian", nativeName: "ქართული" },
	{ id: 98, name: "Wolof", nativeName: "Wollof" },
	{ id: 99, name: "Lithuanian", nativeName: "lietuvių kalba" },
	{ id: 100, name: "Hmong", nativeName: "Hmoob" },
	{ id: 101, name: "Bosnian", nativeName: "Bosanski | босански" },
	{ id: 102, name: "Slovene (Slovenian)", nativeName: "Slovenščina, Slovenski jezik" },
	{ id: 103, name: "Macedonian", nativeName: "Македонски јазик" },
	{ id: 104, name: "Galician", nativeName: "Galego" },
	{ id: 105, name: "Latvian", nativeName: "latviešu valoda" },
	{ id: 106, name: "Yiddish", nativeName: "יידיש" },
	{ id: 107, name: "Chechen", nativeName: "Нохчийн мотт | Nokhchiin mott" },
	{ id: 108, name: "Estonian", nativeName: "eesti keel" },
	{ id: 109, name: "Dinka", nativeName: "Thuɔŋjäŋ" },
	{ id: 110, name: "Pangasinense", nativeName: "Salitan Pangasinan" },
	{ id: 111, name: "Tibetan", nativeName: "ལྷ་སའི་སྐད་" },
	{ id: 112, name: "Sardinian", nativeName: "Sardu | Limba" },
	{ id: 113, name: "Basque", nativeName: "Euskara" },
	{ id: 114, name: "Maltese", nativeName: "Malti" },
	{ id: 115, name: "Welsh", nativeName: "Cymraeg" },
	{ id: 116, name: "Luxembourgish", nativeName: "Lëtzebuergesch" },
	{ id: 117, name: "Icelandic", nativeName: "Íslenska" },
	{ id: 118, name: "Tahitian", nativeName: "Reo Tahiti" },
	{ id: 119, name: "Irish", nativeName: "Gaeilge" },
	{ id: 120, name: "Latin", nativeName: "Latīna" }
];